theme: jekyll-theme-minimal
title: nanoMFG Community
description: Resources for contributers and members of the nanoManufacturing (nanoMFG) project.
show_downloads: False

defaults:
  - scope:
      path: "docs/assets/docs"
    values:
      image: False
